/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class Certifier extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): Certifier;
  methods: {
    validatorSetContract(): TransactionObject<string>;

    initialize(
      _certifiedAddresses: (string)[],
      _validatorSet: string
    ): TransactionObject<void>;

    certify(_who: string): TransactionObject<void>;

    revoke(_who: string): TransactionObject<void>;

    certified(_who: string): TransactionObject<boolean>;

    isInitialized(): TransactionObject<boolean>;
  };
  events: {
    Confirmed: ContractEvent<string>;
    Revoked: ContractEvent<string>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
