/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IBlockRewardAuRaCoins extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): IBlockRewardAuRaCoins;
  methods: {
    transferReward(
      arg0: number | string,
      arg1: string
    ): TransactionObject<void>;

    getDelegatorReward(
      arg0: number | string,
      arg1: number | string,
      arg2: string
    ): TransactionObject<BN>;

    getValidatorReward(
      arg0: number | string,
      arg1: string
    ): TransactionObject<BN>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
