/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IBlockRewardAuRa extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): IBlockRewardAuRa;
  methods: {
    clearBlocksCreated(): TransactionObject<void>;

    initialize(arg0: string): TransactionObject<void>;

    epochsPoolGotRewardFor(arg0: string): TransactionObject<(BN)[]>;

    mintedTotally(): TransactionObject<BN>;

    mintedTotallyByBridge(arg0: string): TransactionObject<BN>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
