/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IOwnerRegistry extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): IOwnerRegistry;
  methods: {
    getOwner(_name: string | number[]): TransactionObject<string>;
  };
  events: {
    Reserved: ContractEvent<{
      name: string;
      owner: string;
      0: string;
      1: string;
    }>;
    Transferred: ContractEvent<{
      name: string;
      oldOwner: string;
      newOwner: string;
      0: string;
      1: string;
      2: string;
    }>;
    Dropped: ContractEvent<{
      name: string;
      owner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
