/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class IReverseRegistry extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): IReverseRegistry;
  methods: {
    hasReverse(_name: string | number[]): TransactionObject<boolean>;

    getReverse(_name: string | number[]): TransactionObject<string>;

    canReverse(_data: string): TransactionObject<boolean>;

    reverse(_data: string): TransactionObject<string>;
  };
  events: {
    ReverseConfirmed: ContractEvent<{
      name: string;
      reverse: string;
      0: string;
      1: string;
    }>;
    ReverseRemoved: ContractEvent<{
      name: string;
      reverse: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
