/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class StakingAuRaTokens extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): StakingAuRaTokens;
  methods: {
    delegatorStakeSnapshot(
      arg0: string,
      arg1: string,
      arg2: number | string
    ): TransactionObject<BN>;

    poolDelegatorIndex(arg0: string, arg1: string): TransactionObject<BN>;

    removePools(): TransactionObject<void>;

    initialize(
      _validatorSetContract: string,
      _initialStakingAddresses: (string)[],
      _delegatorMinStake: number | string,
      _candidateMinStake: number | string,
      _stakingEpochDuration: number | string,
      _stakingEpochStartBlock: number | string,
      _stakeWithdrawDisallowPeriod: number | string
    ): TransactionObject<void>;

    setStakingEpochStartBlock(
      _blockNumber: number | string
    ): TransactionObject<void>;

    moveStake(
      _fromPoolStakingAddress: string,
      _toPoolStakingAddress: string,
      _amount: number | string
    ): TransactionObject<void>;

    setDelegatorMinStake(_minStake: number | string): TransactionObject<void>;

    erc677TokenContract(): TransactionObject<string>;

    rewardWasTaken(
      arg0: string,
      arg1: string,
      arg2: number | string
    ): TransactionObject<boolean>;

    addPool(
      _amount: number | string,
      _miningAddress: string
    ): TransactionObject<void>;

    isInitialized(): TransactionObject<boolean>;

    removePool(_stakingAddress: string): TransactionObject<void>;

    setCandidateMinStake(_minStake: number | string): TransactionObject<void>;

    stakeAmountTotal(arg0: string): TransactionObject<BN>;

    stakeFirstEpoch(arg0: string, arg1: string): TransactionObject<BN>;

    candidateMinStake(): TransactionObject<BN>;

    poolInactiveIndex(arg0: string): TransactionObject<BN>;

    getPools(): TransactionObject<(string)[]>;

    maxWithdrawAllowed(
      _poolStakingAddress: string,
      _staker: string
    ): TransactionObject<BN>;

    stakingEpochStartBlock(): TransactionObject<BN>;

    poolDelegatorsInactive(
      _poolStakingAddress: string
    ): TransactionObject<(string)[]>;

    stakeAmountByCurrentEpoch(
      _poolStakingAddress: string,
      _staker: string
    ): TransactionObject<BN>;

    stakingEpoch(): TransactionObject<BN>;

    stakingEpochEndBlock(): TransactionObject<BN>;

    maxWithdrawOrderAllowed(
      _poolStakingAddress: string,
      _staker: string
    ): TransactionObject<BN>;

    poolDelegatorInactiveIndex(
      arg0: string,
      arg1: string
    ): TransactionObject<BN>;

    getPoolsLikelihood(): TransactionObject<{
      likelihoods: (BN)[];
      sum: BN;
      0: (BN)[];
      1: BN;
    }>;

    stakeWithdrawDisallowPeriod(): TransactionObject<BN>;

    clearUnremovableValidator(
      _unremovableStakingAddress: string
    ): TransactionObject<void>;

    poolDelegators(_poolStakingAddress: string): TransactionObject<(string)[]>;

    orderWithdrawEpoch(arg0: string, arg1: string): TransactionObject<BN>;

    onTokenTransfer(
      arg0: string,
      arg1: number | string,
      arg2: string | number[]
    ): TransactionObject<boolean>;

    getPoolsToBeElected(): TransactionObject<(string)[]>;

    stakeAmount(arg0: string, arg1: string): TransactionObject<BN>;

    isPoolActive(_stakingAddress: string): TransactionObject<boolean>;

    stake(
      _toPoolStakingAddress: string,
      _amount: number | string
    ): TransactionObject<void>;

    poolIndex(arg0: string): TransactionObject<BN>;

    orderWithdraw(
      _poolStakingAddress: string,
      _amount: number | string
    ): TransactionObject<void>;

    stakeLastEpoch(arg0: string, arg1: string): TransactionObject<BN>;

    claimOrderedWithdraw(_poolStakingAddress: string): TransactionObject<void>;

    getPoolsToBeRemoved(): TransactionObject<(string)[]>;

    stakingEpochDuration(): TransactionObject<BN>;

    delegatorMinStake(): TransactionObject<BN>;

    orderedWithdrawAmountTotal(arg0: string): TransactionObject<BN>;

    getPoolsInactive(): TransactionObject<(string)[]>;

    validatorSetContract(): TransactionObject<string>;

    orderedWithdrawAmount(arg0: string, arg1: string): TransactionObject<BN>;

    removeMyPool(): TransactionObject<void>;

    poolToBeRemovedIndex(arg0: string): TransactionObject<BN>;

    incrementStakingEpoch(): TransactionObject<void>;

    MAX_CANDIDATES(): TransactionObject<BN>;

    withdraw(
      _fromPoolStakingAddress: string,
      _amount: number | string
    ): TransactionObject<void>;

    areStakeAndWithdrawAllowed(): TransactionObject<boolean>;

    poolToBeElectedIndex(arg0: string): TransactionObject<BN>;

    claimReward(
      _stakingEpochs: (number | string)[],
      _poolStakingAddress: string
    ): TransactionObject<void>;

    setErc677TokenContract(
      _erc677TokenContract: string
    ): TransactionObject<void>;

    getRewardAmount(
      _stakingEpochs: (number | string)[],
      _poolStakingAddress: string,
      _staker: string
    ): TransactionObject<{
      tokenRewardSum: BN;
      nativeRewardSum: BN;
      0: BN;
      1: BN;
    }>;
  };
  events: {
    ClaimedReward: ContractEvent<{
      fromPoolStakingAddress: string;
      staker: string;
      stakingEpoch: BN;
      tokensAmount: BN;
      nativeCoinsAmount: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
      4: BN;
    }>;
    AddedPool: ContractEvent<string>;
    ClaimedOrderedWithdrawal: ContractEvent<{
      fromPoolStakingAddress: string;
      staker: string;
      stakingEpoch: BN;
      amount: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    MovedStake: ContractEvent<{
      fromPoolStakingAddress: string;
      toPoolStakingAddress: string;
      staker: string;
      stakingEpoch: BN;
      amount: BN;
      0: string;
      1: string;
      2: string;
      3: BN;
      4: BN;
    }>;
    OrderedWithdrawal: ContractEvent<{
      fromPoolStakingAddress: string;
      staker: string;
      stakingEpoch: BN;
      amount: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    PlacedStake: ContractEvent<{
      toPoolStakingAddress: string;
      staker: string;
      stakingEpoch: BN;
      amount: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    RemovedPool: ContractEvent<string>;
    WithdrewStake: ContractEvent<{
      fromPoolStakingAddress: string;
      staker: string;
      stakingEpoch: BN;
      amount: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
